#!/bin/sh

dir="~/dotfiles"
repo="git@github.com:aht/dotfiles.git"

debug=0
if [ "$1" = "-d" ]; then
    debug=1
    shift
fi

for host in $@; do
   echo "[INFO] Pushing dotfiles to $host ..."
   ssh $host "
       if [ $debug = 1 ]; then
           set -x
       fi
       if [ -d $dir ]; then
           cd $dir
           git fetch
           git merge origin/master
           yes | make install 2>/dev/null
       else
           git clone $repo $dir
           cd $dir
           yes | make install 2>/dev/null
       fi
   "
done;
