#!/bin/sh

dir="~/dotfiles"
repo="https://github.com/aht/dotfiles.git"

debug=0
if [ "$1" = "-d" ]; then
    debug=1
    shift
fi

for host in $@; do
   echo "[INFO] Pushing dotfiles to $host ..."
   ssh $host "
       if [ $debug = 1 ]; then
           set -x
       fi
       if [ -d $dir ]; then
           cd $dir
           git fetch
           git merge origin/master
           yes | make install
           echo >&2  # last char of stderr is not newline
       else
           git clone $repo $dir
           cd $dir
           yes | make install
           echo >&2  # last char of stderr is not newline
       fi
   " &
done

echo "[INFO] Waiting for all processes to complete ..."
wait
echo "[INFO] Done!"
